version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  web:
    image: aayyusssh/corider_assignment_updated-flask_app:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
